{% set name = "xarray-eopf" %}
{% set version = "0.2.1" %}
{% set python_min = "3.10" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/EOPF-Sample-Service/xarray-eopf/archive/v{{ version }}.tar.gz
  sha256: 25b4fecd5bf5fabeaf8b7507145593fb9df53178bf9b1ca14db600d50d162869

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation

requirements:
  host:
    - python {{ python_min }}
    - pip
    - setuptools
  run:
    - python >={{ python_min }}
    - aiohttp
    - dask
    - dask-image
    - fsspec
    - numba
    - numpy
    - pyproj
    - requests
    - s3fs
    - xarray >=2024.10
    - xcube-resampling
    - zarr >=2,<3.0

test:
  imports:
    - xarray_eopf
  commands:
    - pip check
  requires:
    - python {{ python_min }}
    - pip

about:
  summary: A backend implementation for xarray that allows for analysis-ready reading of ESA EOPF data products.
  home: https://github.com/EOPF-Sample-Service/xarray-eopf
  license: Apache-2.0
  license_family: Apache
  license_file: LICENSE
  description: xarray-eopf is a Python package
  dev_url: https://github.com/EOPF-Sample-Service/xarray-eopf

extra:
  recipe-maintainers:
    - forman
    - konstntokas
    - pont-us
